In [1]:
# Import Dependencies
import pandas as pd

In [4]:
# Make a reference to the books.csv file path

# Import the books.csv file as a DataFrame
df = pd.read_csv("books.csv")
df.head()

,id,book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...
1,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPré",1997.0,Harry Potter and the Philosopher's Stone,...,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...
2,3,41865,41865,3212258,226,316015849,9.780316e+12,Stephenie Meyer,2005.0,Twilight,...,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...
3,4,2657,2657,3275794,487,61120081,9.780061e+12,Harper Lee,1960.0,To Kill a Mockingbird,...,3198671,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...
4,5,4671,4671,245494,1356,743273567,9.780743e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,...,2683664,2773745,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...

In [8]:
# Remove unecessary columns from the DataFrame and save the new DataFrame
# Only keep: "isbn", "original_publication_year", "original_title", "authors",
# "ratings_1", "ratings_2", "ratings_3", "ratings_4", "ratings_5"
df_cleaned = df[["isbn", "original_publication_year", "original_title", "authors",
             "ratings_1", "ratings_2", "ratings_3", "ratings_4", "ratings_5"]]
df_cleaned.head()

,isbn,original_publication_year,original_title,authors,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5
0,439023483,2008.0,The Hunger Games,Suzanne Collins,66715,127936,560092,1481305,2706317
1,439554934,1997.0,Harry Potter and the Philosopher's Stone,"J.K. Rowling, Mary GrandPré",75504,101676,455024,1156318,3011543
2,316015849,2005.0,Twilight,Stephenie Meyer,456191,436802,793319,875073,1355439
3,61120081,1960.0,To Kill a Mockingbird,Harper Lee,60427,117415,446835,1001952,1714267
4,743273567,1925.0,The Great Gatsby,F. Scott Fitzgerald,86236,197621,606158,936012,947718

In [9]:
# Rename the headers to be more explanatory
df_cleaned = df_cleaned.rename(columns={"isbn": "ISBN", "original_publication_year": "Publication Year",
                                        "original_title": "Original Title", "authors": "Authors",
                                        "ratings_1": "One Star Reviews", "ratings_2": "Two Star Reviews",
                                        "ratings_3": "Three Star Reviews", "ratings_4": "Four Star Reviews",
                                        "ratings_5": "Five Star Reviews"})
df_cleaned

,ISBN,Publication Year,Original Title,Authors,One Star Reviews,Two Star Reviews,Three Star Reviews,Four Star Reviews,Five Star Reviews
0,439023483,2008.0,The Hunger Games,Suzanne Collins,66715,127936,560092,1481305,2706317
1,439554934,1997.0,Harry Potter and the Philosopher's Stone,"J.K. Rowling, Mary GrandPré",75504,101676,455024,1156318,3011543
2,316015849,2005.0,Twilight,Stephenie Meyer,456191,436802,793319,875073,1355439
3,61120081,1960.0,To Kill a Mockingbird,Harper Lee,60427,117415,446835,1001952,1714267
4,743273567,1925.0,The Great Gatsby,F. Scott Fitzgerald,86236,197621,606158,936012,947718
5,525478817,2012.0,The Fault in Our Stars,John Green,47994,92723,327550,698471,1311871
6,618260307,1937.0,The Hobbit or There and Back Again,J.R.R. Tolkien,46023,76784,288649,665635,1119718
7,316769177,1951.0,The Catcher in the Rye,J.D. Salinger,109383,185520,455042,661516,709176
8,1416524797,2000.0,Angels & Demons,Dan Brown,77841,145740,458429,716569,680175
9,679783261,1813.0,Pride and Prejudice,Jane Austen,54700,86485,284852,609755,1155673
10,1594480001,2003.0,The Kite Runner,Khaled Hosseini,34288,59980,226062,628174,929591
11,62024035,2011.0,Divergent,Veronica Roth,36315,82870,310297,673028,1114304
12,451524934,1949.0,Nineteen Eighty-Four,"George Orwell, Erich Fromm, Celâl Üster",41845,86425,324874,692021,908229
13,452284244,1945.0,Animal Farm: A Fairy Story,George Orwell,66854,135147,433432,698642,648912
14,553296981,1947.0,Het Achterhuis: Dagboekbrieven 14 juni 1942 - ...,"Anne Frank, Eleanor Roosevelt, B.M. Mooyaart-D...",45225,91270,355756,656870,875372
15,307269752,2005.0,Män som hatar kvinnor,"Stieg Larsson, Reg Keeland",54835,86051,285413,667485,836050
16,439023491,2009.0,Catching Fire,Suzanne Collins,10492,48030,262010,687238,980309
17,043965548X,1999.0,Harry Potter and the Prisoner of Azkaban,"J.K. Rowling, Mary GrandPré, Rufus Beck",6716,20413,166129,509447,1266670
18,618346252,1954.0,The Fellowship of the Ring,J.R.R. Tolkien,38031,55862,202332,493922,1042394
19,439023513,2010.0,Mockingjay,Suzanne Collins,30144,110498,373060,618271,738775
20,439358078,2003.0,Harry Potter and the Order of the Phoenix,"J.K. Rowling, Mary GrandPré",9528,31577,180210,494427,1124806
21,316166685,2002.0,The Lovely Bones,Alice Sebold,62777,131188,404699,583575,479323
22,439064864,1998.0,Harry Potter and the Chamber of Secrets,"J.K. Rowling, Mary GrandPré",8253,42251,242345,548266,1065084
23,439139600,2000.0,Harry Potter and the Goblet of Fire,"J.K. Rowling, Mary GrandPré",6676,20210,151785,494926,1195045
24,545010225,2007.0,Harry Potter and the Deathly Hallows,"J.K. Rowling, Mary GrandPré",9363,22245,113646,383914,1318227
25,307277674,2003.0,The Da Vinci Code,Dan Brown,71345,126493,340790,539277,479387
26,439785960,2005.0,Harry Potter and the Half-Blood Prince,"J.K. Rowling, Mary GrandPré",7308,21516,136333,459028,1161491
27,140283331,1954.0,Lord of the Flies,William Golding,92779,160295,425648,564916,427846
28,743477111,1595.0,An Excellent conceited Tragedie of Romeo and J...,"William Shakespeare, Robert Jackson",57980,153179,452673,519822,489235
29,297859382,2012.0,Gone Girl,Gillian Flynn,38874,80807,280331,616031,610476
...,...,...,...,...,...,...,...,...,...
9970,NaN,2011.0,NaN,Melody Anne,395,1182,4378,6060,5591
9971,99282968,1999.0,Bagombo Snuff Box,Kurt Vonnegut Jr.,78,548,2817,3430,1724
9972,609805797,1999.0,The Seven Principles for Making Marriage Work:...,"John M. Gottman, Nan Silver",126,334,1604,3446,4507
9973,553153382,1978.0,Anastasia Krupnik,Lois Lowry,440,603,3062,4185,4229
9974,1857236653,1985.0,The King Beyond the Gate,David Gemmell,49,249,1968,4174,3867
9975,778325806,2009.0,Sea Glass,Maria V. Snyder,118,655,3685,6185,5294
9976,804113475,1995.0,Ladder of Years,Anne Tyler,214,854,3714,4827,2620
9977,679750150,1963.0,午後の曳航 [Gogo no eikō],"Yukio Mishima, John Nathan",142,590,2414,4551,2844
9978,312940661,1964.0,When the Lion Feeds,Wilbur Smith,64,268,1648,3732,3869
9979,764200739,2006.0,The Measure of a Lady,Deeanne Gist,187,608,2337,3355,3476
9980,739455834,2005.0,The Twelfth Card,Jeffery Deaver,72,390,2874,5155,3643
9981,385344422,2016.0,Feverborn,Karen Marie Moning,179,521,2308,4779,6407
9982,2849659266,2009.0,青の祓魔師 2,Kazue Kato,32,152,1025,2479,6171
9983,140255087,1978.0,The Snow Leopard,Peter Matthiessen,145,406,1586,3393,4002
9984,425176932,2000.0,Tom Clancy's Net Force: Breaking Point,"Steve Perry, Tom Clancy, Steve Pieczenik",268,684,2349,2456,2068
9985,310257689,2006.0,Night Light: A Restoration Novel,Terri Blackstock,96,172,1115,2658,4821
9986,312651198,2010.0,Chasing The Night,Iris Johansen,113,331,2127,3957,4436
9987,674017722,1971.0,A Theory of Justice,John Rawls,234,607,2001,3171,3095
9988,NaN,2012.0,Out of the Dark,Quinn Loftis,72,229,1263,3280,8770
9989,140143912,1989.0,The Mambo Kings Play Songs of Love,Oscar Hijuelos,374,836,2692,3513,2361
9990,385425139,1991.0,The Famished Road,Ben Okri,465,815,2046,2895,2654
9991,575113294,2012.0,The Red Knight,Miles Cameron,232,491,1375,3712,4292
9992,224079948,2008.0,The Time-Traveller's Guide to Medieval England...,Ian Mortimer,236,521,2497,4790,4071
9993,810983559,2009.0,"The Everafter War (The Sisters Grimm, #7)","Michael Buckley, Peter Ferguson",110,289,1745,3989,6832
9994,1416523723,1924.0,"Billy Budd, Sailor",Herman Melville,1478,2225,3805,2985,1617
9995,441019455,2010.0,Bayou Moon,Ilona Andrews,105,575,3538,7860,6778
9996,067973371X,1990.0,Means of Ascent,Robert A. Caro,303,551,1737,3389,6972
9997,039330762X,1977.0,The Mauritius Command,Patrick O'Brian,11,111,1191,4240,5180
9998,61711527,2011.0,Cinderella Ate My Daughter: Dispatches from th...,Peggy Orenstein,275,1002,3765,4577,2375
9999,375700455,1998.0,The First World War,John Keegan,117,345,2031,4138,3069

In [11]:
# Push the remade DataFrame to a new CSV file
df_cleaned.to_csv("goodreads_clean.csv",index=False,header=True)