In [1]:
import pandas as pd
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Create a reference to the CSV and import it into a Pandas DataFrame
csv_path = "EclipseBugs.csv"
eclipse_df = pd.read_csv(csv_path)
eclipse_df.head()

,Bug ID,Product,Component,Assignee,Status,Resolution,Summary,Changed,Assignee Real Name,Classification,...,Number of Comments,Opened,OS,Priority,Reporter,Reporter Real Name,Severity,Target Milestone,Version,Votes
0,3638,JDT,UI,aeschli,VERIFIED,FIXED,Package Viewer: order resource folders before ...,1/17/2002 7:28,Martin Aeschlimann,Eclipse,...,3,10/10/2001 22:58,Windows NT,P1,aeschli,Martin Aeschlimann,major,---,2,0
1,3854,JDT,UI,aeschli,VERIFIED,FIXED,Wrong execution's classpath. (1GEY0W0),1/18/2002 4:02,Martin Aeschlimann,Eclipse,...,5,10/10/2001 23:01,Windows NT,P1,david_audel,David Audel,normal,---,2,0
2,4188,JDT,UI,aeschli,VERIFIED,FIXED,type hierachy - typo (1GJW2XJ),1/28/2002 3:12,Martin Aeschlimann,Eclipse,...,3,10/10/2001 23:07,Windows 2000,P1,erich_gamma,Erich Gamma,normal,---,2,0
3,5115,JDT,Debug,aeschli,VERIFIED,FIXED,Workspace source locator fails with mulitple p...,11/13/2001 10:11,Martin Aeschlimann,Eclipse,...,10,10/19/2001 13:41,Windows 2000,P1,darin.eclipse,Darin Wright,normal,---,2,0
4,5820,JDT,UI,aeschli,VERIFIED,FIXED,Close all editors brings up hierarchy of object,11/20/2001 16:22,Martin Aeschlimann,Eclipse,...,5,11/12/2001 18:18,Windows 2000,P1,jed.anderson,Jed Anderson,normal,---,2,0

In [10]:
# Removing the newlines from column headers
eclipse_df = eclipse_df.rename(columns={"Bug\nID": "Bug ID",
                                        "Assignee\nReal\nName": "Assignee Real Name",
                                        "Number of\nComments": "Number of Comments",
                                        "Reporter\nReal\nName": "Reporter Real Name",
                                        "Target\nMilestone": "Target Milestone"})
eclipse_df.columns

Index(['Bug ID', 'Product', 'Component', 'Assignee', 'Status', 'Resolution',
       'Summary', 'Changed', 'Assignee Real Name', 'Classification',
       'Hardware', 'Number of Comments', 'Opened', 'OS', 'Priority',
       'Reporter', 'Reporter Real Name', 'Severity', 'Target Milestone',
       'Version', 'Votes'],
      dtype='object')

In [11]:
# Finding the average number of comments per bug
average_comments = eclipse_df["Number of Comments"].mean()
average_comments

8.75

In [12]:
# Grouping the DataFrame by "Assignee"
assignee_group = eclipse_df.groupby("Assignee")

# Count how many of each component Assignees worked on and create DataFrame
assignee_work = pd.DataFrame(assignee_group["Component"].value_counts())
assignee_work.head()

                                Component
Assignee       Component
Aaron_Ferguson UI                      10
Adam_Schlegel  UI                       7
ChrisAustin    User Assistance          3
Claude_Knaus   UI                      31
               Text                     7

In [13]:
# Rename the "Component" column to "Component Bug Count"
assignee_work = assignee_work.rename(columns={"Component": "Component Bug Count"})
assignee_work.head()

                                Component Bug Count
Assignee       Component
Aaron_Ferguson UI                                10
Adam_Schlegel  UI                                 7
ChrisAustin    User Assistance                    3
Claude_Knaus   UI                                31
               Text                               7

In [14]:
# Find the percentage of bugs overall fixed by each Assignee
total_bugs = eclipse_df["Assignee"].count()
bugs_per_user = assignee_group["Assignee"].value_counts()
# #bugs_per_user = bugs_per_user.reset_index(drop=False)

# user_bug_percent = pd.DataFrame((bugs_per_user/total_bugs)*100)
# # user_bug_percent = user_bug_percent.rename(columns={"Assignee": "Percent of Total Bugs"})
# # user_bug_percent = user_bug_percent.reset_index(drop=False)
# user_bug_percent.head()
bugs_per_user

Assignee             Assignee
Aaron_Ferguson       Aaron_Ferguson          10
Adam_Schlegel        Adam_Schlegel            7
ChrisAustin          ChrisAustin              3
Claude_Knaus         Claude_Knaus            38
Curtis_Windatt       Curtis_Windatt           6
Darin_Swanson        Darin_Swanson          297
James_Moody          James_Moody              2
Karice_McIntyre      Karice_McIntyre          4
Kevin_McGuire        Kevin_McGuire            6
Lars.Vogel           Lars.Vogel               3
Michael_Rennie       Michael_Rennie          37
Mike_Wilson          Mike_Wilson              2
Olivier_Thomann      Olivier_Thomann         25
Platform-UI-Inbox    Platform-UI-Inbox        4
Randy_Giffen         Randy_Giffen             8
Silenio_Quarti       Silenio_Quarti          11
Szymon.Brandys       Szymon.Brandys          16
Tod_Creasey          Tod_Creasey            459
Vikas.Chandra        Vikas.Chandra            3
a.aswani             a.aswani                 2
abhishek.kishore     abhishek.kishore         8
abuzila              abuzila                  1
achilles-86          achilles-86              1
achim.demelt         achim.demelt             1
aclement             aclement                 6
aeschli              aeschli                627
aferrazz             aferrazz                 1
agarcher             agarcher                23
ahunter.eclipse      ahunter.eclipse          3
aiproulx             aiproulx                 1
                                           ...
rafael.oliveira      rafael.oliveira          1
raksha.vasisht       raksha.vasisht          16
rthakkar             rthakkar                 5
ryan_cooper          ryan_cooper             10
sarika.sinha         sarika.sinha             1
sasikanth.bharadwaj  sasikanth.bharadwaj      1
satyam.kandula       satyam.kandula           1
serge                serge                    1
silvio_boehler       silvio_boehler           1
simon_arsenault      simon_arsenault          6
snorthov             snorthov                 2
sonia_dimitrov       sonia_dimitrov           2
sravankumarl         sravankumarl             1
srikanth_sankaran    srikanth_sankaran        2
stderr               stderr                   1
stephan.herrmann     stephan.herrmann         4
susan                susan                    9
sxenos               sxenos                  42
szymon.ptaszkiewicz  szymon.ptaszkiewicz      2
t.s.maeder           t.s.maeder              13
teicher-bugzilla     teicher-bugzilla         3
till_bay             till_bay                21
tobias_widmer        tobias_widmer           38
tom.schindl          tom.schindl              1
tomasz.zarna         tomasz.zarna             9
unknown              unknown                  2
valentam             valentam                30
veronika_irvine      veronika_irvine          2
wassim.melhem        wassim.melhem            4
zhiyongl             zhiyongl                 1
Name: Assignee, Length: 205, dtype: int64

In [ ]:
# Merge the "Percent of Total Bugs Assigned" into the DataFrame
assignee_work = assignee_work.merge(user_bug_percent, on="Assignee")

# Remove the extra columns
assignee_work = assignee_work[["Assignee", "Percent of Total Bugs", "Component", "Component Bug Count"]]
assignee_work.head()