# Winnining Wrestlers Entertainment

In this activity you will be taking four seperate csvs that were scraped down from a wrestling database, merging them together, and then creating charts to visualize a wrestler's wins and losses over the course of four years.

### Part 1 - Macho Merging

* You will likely need to perform three different merges over the course of this activity, changing the names of your columns as you go along.

In [1]:
# Import the necessary modules
import pandas as pd
import matplotlib as plt

In [2]:
# Bring each CSV into a separate data frame
df_2013 = pd.read_csv("WWE-Data-2013.csv")
df_2014 = pd.read_csv("WWE-Data-2014.csv")
df_2015 = pd.read_csv("WWE-Data-2015.csv")
df_2016 = pd.read_csv("WWE-Data-2016.csv")

In [3]:
# Merge the first two datasets (2013 and 2014) on "Wrestler" so that no data is lost (should be 182 rows)
merged = df_2013.merge(df_2014, suffixes=("_2013", "_2014"), on="Wrestler", how="outer")
merged.head()

,Wrestler,Wins_2013,Losses_2013,Draws_2013,Wins_2014,Losses_2014,Draws_2014
0,Daniel Bryan,177.0,37.0,6.0,35.0,16.0,2.0
1,Dean Ambrose,70.0,134.0,4.0,129.0,36.0,2.0
2,Antonio Cesaro,80.0,126.0,1.0,5.0,24.0,0.0
3,Seth Rollins,50.0,150.0,4.0,87.0,105.0,4.0
4,Randy Orton,129.0,63.0,8.0,33.0,87.0,5.0

In [5]:
# Merge our newly combined dataframe with the 2015 dataframe
merged = merged.merge(df_2015, on="Wrestler", how="outer")
merged.head()

,Wrestler,Wins_2013,Losses_2013,Draws_2013,Wins_2014,Losses_2014,Draws_2014,Wins,Losses,Draws
0,Daniel Bryan,177.0,37.0,6.0,35.0,16.0,2.0,51.0,7.0,0.0
1,Dean Ambrose,70.0,134.0,4.0,129.0,36.0,2.0,150.0,63.0,5.0
2,Antonio Cesaro,80.0,126.0,1.0,5.0,24.0,0.0,NaN,NaN,NaN
3,Seth Rollins,50.0,150.0,4.0,87.0,105.0,4.0,51.0,124.0,1.0
4,Randy Orton,129.0,63.0,8.0,33.0,87.0,5.0,81.0,10.0,1.0

In [7]:
# Merge our newly combined dataframe with the 2016 dataframe
merged = merged.merge(df_2016, how="outer", suffixes=("_2015", "_2016"), on="Wrestler")
merged.head()

,Wrestler,Wins_2013,Losses_2013,Draws_2013,Wins_2014,Losses_2014,Draws_2014,Wins_2015,Losses_2015,Draws_2015,Wins_2016,Losses_2016,Draws_2016
0,Daniel Bryan,177.0,37.0,6.0,35.0,16.0,2.0,51.0,7.0,0.0,NaN,NaN,NaN
1,Dean Ambrose,70.0,134.0,4.0,129.0,36.0,2.0,150.0,63.0,5.0,133.0,67.0,4.0
2,Antonio Cesaro,80.0,126.0,1.0,5.0,24.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Seth Rollins,50.0,150.0,4.0,87.0,105.0,4.0,51.0,124.0,1.0,39.0,75.0,4.0
4,Randy Orton,129.0,63.0,8.0,33.0,87.0,5.0,81.0,10.0,1.0,39.0,21.0,0.0

In [11]:
merged = merged.fillna(0) # Replace missing values by 0
merged["Total Wins"] = merged["Wins_2013"]+merged["Wins_2014"]+merged["Wins_2015"]+merged["Wins_2016"]
merged["Total Losses"] = merged["Losses_2013"]+merged["Losses_2014"]+merged["Losses_2015"]+merged["Losses_2016"]
merged["Total Draws"] = merged["Draws_2013"]+merged["Draws_2014"]+merged["Draws_2015"]+merged["Draws_2016"]
merged["Total Matches"] = merged["Total Wins"]+merged["Total Losses"]+merged["Total Draws"]
merged.head()

,Wrestler,Wins_2013,Losses_2013,Draws_2013,Wins_2014,Losses_2014,Draws_2014,Wins_2015,Losses_2015,Draws_2015,Wins_2016,Losses_2016,Draws_2016,Total Wins,Total Losses,Total Draws,Total Matches
0,Daniel Bryan,177.0,37.0,6.0,35.0,16.0,2.0,51.0,7.0,0.0,0.0,0.0,0.0,263.0,60.0,8.0,331.0
1,Dean Ambrose,70.0,134.0,4.0,129.0,36.0,2.0,150.0,63.0,5.0,133.0,67.0,4.0,482.0,300.0,15.0,797.0
2,Antonio Cesaro,80.0,126.0,1.0,5.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,85.0,150.0,1.0,236.0
3,Seth Rollins,50.0,150.0,4.0,87.0,105.0,4.0,51.0,124.0,1.0,39.0,75.0,4.0,227.0,454.0,13.0,694.0
4,Randy Orton,129.0,63.0,8.0,33.0,87.0,5.0,81.0,10.0,1.0,39.0,21.0,0.0,282.0,181.0,14.0,477.0

In [15]:
wres_100_match = merged.loc[(merged["Total Matches"] >= 100) &
                            (merged["Wins_2013"] > 0) &
                            (merged["Wins_2016"] > 0)]
wres_100_match.head()

,Wrestler,Wins_2013,Losses_2013,Draws_2013,Wins_2014,Losses_2014,Draws_2014,Wins_2015,Losses_2015,Draws_2015,Wins_2016,Losses_2016,Draws_2016,Total Wins,Total Losses,Total Draws,Total Matches
1,Dean Ambrose,70.0,134.0,4.0,129.0,36.0,2.0,150.0,63.0,5.0,133.0,67.0,4.0,482.0,300.0,15.0,797.0
3,Seth Rollins,50.0,150.0,4.0,87.0,105.0,4.0,51.0,124.0,1.0,39.0,75.0,4.0,227.0,454.0,13.0,694.0
4,Randy Orton,129.0,63.0,8.0,33.0,87.0,5.0,81.0,10.0,1.0,39.0,21.0,0.0,282.0,181.0,14.0,477.0
5,Roman Reigns,49.0,140.0,5.0,118.0,28.0,4.0,187.0,19.0,7.0,142.0,12.0,5.0,496.0,199.0,21.0,716.0
6,Ryback,103.0,88.0,3.0,43.0,114.0,1.0,138.0,34.0,2.0,37.0,17.0,1.0,321.0,253.0,7.0,581.0

In [20]:
user_input = input("Which wrestler you want to analyze? ")
wrest_wins = wres_100_match.loc[user_input, ["Wins_2013", "Wins_2014", "Wins_2015", "Wins_2016"]]
wrest_wins

Which wrestler you want to analyze? Dean Ambrose

KeyError: 'Dean Ambrose'